name: ubuntu

on:
    push:
        branches:
            - '*'

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - ubuntu-18.04
                - ubuntu-20.04
            perl-version:
                - '5.10'
                - '5.12'
                - '5.14'
                - '5.16'
                - '5.18'
                - '5.20'
                - '5.22'
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
                - '5.32'
                - 'latest'

        container:
            image: perl:${{ matrix.perl-version }}
        steps:
            - name: Platform check
              run: uname -a
            - name: Perl version check
              run: perl -V
            - name: Install cpanm and multiple modules
              run: |
                curl -L https://cpanmin.us | perl - App::cpanminus
                cpanm JSON::Parse
                cpanm JSON::Create
                cpanm IO::Socket
                cpanm Unicode::UTF8
                cpanm boolean
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
